##############################################################
# Sample: Ansible Playbook for creating ACLs on Cisco IOS XE
# Author: Simon Hart <sihart@cisco.com>
#
# mergeacljinja.yaml
# Will configure the router via the Ansible netconf plugin:
# Add entries to an extended access lists using the Cisco Native 
# YANG Model.  The mergeacls.yaml file should be populated with 
# variables for the addition/change of AC entries.
##############################################################
---
- name: Provision IOS XE Devices
  hosts: vagrant
  connection: local
  gather_facts: false

  vars_files:
    - ./accesslists/mergeacls.yaml

  tasks:
     - name: Configure Jinja
       template: 
         src: "{{mergeaccess}}"
         dest: "./templates/acls.xml"

     - name: Configure ACLS
       netconf_config:
         host: "{{mgmt_ip}}"
         port: "{{netconf_port}}"
         hostkey_verify: false
         username: "{{username}}"
         password: "{{password}}"
         src: "{{acls}}"

    
              
